version: '3.7'
services:
  backend:
    build:
      context: ./living_stories
    container_name: living_stories_backend
    ports:
      - "8080:8080"
    env_file:
      - ./front_end/.env
    volumes:
      - backend-data:/path/to/backend/data
    depends_on:
      - db

  frontend:
    build: 
        context: ./front_end
    container_name: living_stories_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./front_end/.env
    depends_on:
      - backend


  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./front_end/.env
    volumes:
      - db-data:/var/lib/postgresql/data

  volumes:
    backend-data:
    db-data:
